name: Reusable Static Mattermost deployment Notify Workflow

on:
  workflow_call:
    inputs:
      application-full-name:
        required: true
        type: string
      deployed-domain:
        required: true
        type: string
    secrets:
      MATTERMOST_NOTIFY_HOOK_URL:
        required: true

jobs:
  mattermost-notify-instance-url:
    runs-on: ubuntu-latest
    steps:
      - name: Notify mattermost canal
        run: |
          curl --header "Content-Type:application/json" -d "{\"text\":\"Une nouvelle version pour: ${{ inputs.application-full-name }} est disponible.\n [Tester la d√©mo](https://${{ inputs.deployed-domain }})  \"}" ${{ secrets.MATTERMOST_NOTIFY_HOOK_URL }}
