name: zGitOps - On push create a pull request between the branch and master if it does not exist
on:
  push:
    branches:
      - '**'
#      - 'build/*'
#      - 'chore/*'
#      - 'ci/*'
#      - 'docs/*'
#      - 'feat/*'
#      - 'fix/*'
#      - 'perf/*'
#      - 'refactor/*'
#      - 'revert/*'
#      - 'style/*'
#      - 'test/*'
#      - 'release/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request if it does not exist
        uses: actions/github-script@v6
        id: test
        with:
          result-encoding: string
          script: |
            const { repo, owner } = context.repo;
            const head = '${{ github.ref_name }}';
            // Checks if an open pr with the same head and base exist
            const pullRequestsListResponse = await github.rest.pulls.list({owner, repo, head, state: 'open', base: 'master'});
            // If we did find a pr return with process success
            if(pullRequestsListResponse?.data?.length > 0) return 0;
            const result = await github.rest.pulls.create({
              title: '${{ github.ref_name }}',
              owner,
              repo,
              head,
              base: 'master',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
